"""
Interactive script to set up Supabase credentials
"""
import os
from pathlib import Path

def setup_supabase():
    """Interactive setup for Supabase credentials"""
    print("=" * 60)
    print("SUPABASE SETUP FOR STEM-FACE-DASHBOARD")
    print("=" * 60)
    print("\nThis script will help you configure your new Supabase project.")
    print("\nTo find your Supabase credentials:")
    print("1. Go to https://app.supabase.com")
    print("2. Select your 'stem-face-dashboard' project")
    print("3. Go to Settings > API")
    print("4. Copy the 'Project URL' and 'anon/public' key")
    print("\n" + "-" * 60)
    
    # Get Supabase URL
    print("\nEnter your Supabase Project URL:")
    print("(Example: https://abcdefghijklmnop.supabase.co)")
    supabase_url = input("SUPABASE_URL: ").strip()
    
    if not supabase_url:
        print("ERROR: Supabase URL is required")
        return False
    
    if not supabase_url.startswith("https://"):
        print("WARNING: URL should start with https://")
    
    # Get Supabase Key
    print("\nEnter your Supabase anon/public key:")
    print("(This is a long JWT token starting with 'eyJ...')")
    supabase_key = input("SUPABASE_KEY: ").strip()
    
    if not supabase_key:
        print("ERROR: Supabase key is required")
        return False
    
    # Get or generate secret key
    print("\nEnter a secret key for Flask sessions (or press Enter to generate one):")
    secret_key = input("SECRET_KEY: ").strip()
    
    if not secret_key:
        import secrets
        secret_key = secrets.token_urlsafe(32)
        print(f"Generated SECRET_KEY: {secret_key[:20]}...")
    
    # Create .env file
    env_file = Path(".env")
    
    # Check if .env already exists
    if env_file.exists():
        print(f"\nWARNING: .env file already exists!")
        overwrite = input("Do you want to overwrite it? (yes/no): ").strip().lower()
        if overwrite != 'yes':
            print("Setup cancelled.")
            return False
    
    # Write .env file
    env_content = f"""# Supabase Configuration
# Generated by setup_supabase.py
SUPABASE_URL={supabase_url}
SUPABASE_KEY={supabase_key}

# Flask Secret Key
SECRET_KEY={secret_key}

# Optional: Feature Flags
# ENABLE_FACE_RECOGNITION=false
# ENABLE_LEGACY_ANALYTICS=false
# MAINTENANCE_MODE=false
"""
    
    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        print(f"\n[SUCCESS] .env file created successfully!")
        print(f"Location: {env_file.absolute()}")
        
        # Test connection
        print("\n" + "-" * 60)
        print("Testing Supabase connection...")
        test_connection(supabase_url, supabase_key)
        
        return True
        
    except Exception as e:
        print(f"\n[ERROR] Failed to create .env file: {e}")
        return False

def test_connection(url, key):
    """Test the Supabase connection"""
    try:
        from supabase import create_client
        supabase = create_client(url, key)
        print("[OK] Supabase client created successfully")
        
        # Try a simple query
        try:
            response = supabase.table('users').select('count').limit(1).execute()
            print("[OK] Database connection successful")
        except Exception as e:
            error_msg = str(e)
            if 'relation' in error_msg.lower() or 'does not exist' in error_msg.lower():
                print("[INFO] Connection works, but 'users' table doesn't exist yet")
                print("       You may need to create database tables in Supabase")
            else:
                print(f"[WARNING] Connection test: {e}")
        
        print("\n[SUCCESS] Setup complete! Your Supabase credentials are configured.")
        print("\nNext steps:")
        print("1. Create database tables in your Supabase project")
        print("2. Run the app to test authentication")
        print("3. Check Supabase dashboard for any additional setup")
        
    except Exception as e:
        print(f"[ERROR] Failed to connect to Supabase: {e}")
        print("Please check your credentials and try again.")

if __name__ == "__main__":
    setup_supabase()

